Dev/artifacts added (#36)
Artifacts are now available for .dmapp files generated by automation scripts directly in GitHub.

diff --git a/.github/workflows/Automation Master SDK Workflow.yml b/.github/workflows/Automation Master SDK Workflow.yml
--- a/.github/workflows/Automation Master SDK Workflow.yml
+++ b/.github/workflows/Automation Master SDK Workflow.yml
@@ -218,53 +218,18 @@ jobs:
             exit(1)
         shell: python
 
-  artifact_creation_registration:
-    name: Artifact Registration and Upload
-    if: inputs.referenceType == 'tag'
+  artifact_creation:
+    name: Artifact Creation
     runs-on: ubuntu-latest
-    needs: validate_skyline_quality_gate
-    env:
-      result-artifact-id: none
-    outputs:
-      artifact-id: ${{ env.result-artifact-id }}
-      #artifact-id-development: ${{ steps.upload-step-development.outputs.ARTIFACT_ID }}
-
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Initialize
-        run: |
-          echo "workspace" ${{ github.workspace }}
-          echo "ref name" ${{ inputs.referenceName }}
-          echo "run number" ${{ inputs.runNumber }}
-          echo "ref type" ${{ inputs.referenceType }}
-          echo "repository" ${{ inputs.repository }}
 
       - name: Find .sln file
         id: findSlnFile        
         run: |
           echo solutionFilePath=$(find . -type f -name '*.sln') >> $GITHUB_OUTPUT
-        shell: bash
-        
-      - name: Find branch
-        id: findBranch
-        run: |
-          #!/bin/bash
-          set -e  # Exit immediately if a command exits with a non-zero status.
-          
-          # Capture the branches containing the tag and process them
-          branches="$(git branch --contains tags/${{ inputs.referenceName }} -r | grep 'origin/' | grep -vE '.*/.*/' | sed 's#origin/##' | paste -sd ",")"
-          
-          # Append to GitHub Actions output
-          echo "branch=${branches}" >> $GITHUB_OUTPUT
-        shell: bash 
-
-      - name: Target Branch
-        id: showResult
-        run: echo "${{ steps.findBranch.outputs.branch }}"
+        shell: bash   
         
         # TODO: Refactor this in the future to a single stage with a loop that adds all the sources you specify.
       - name: Enable Skyline GitHub NuGet Registry
@@ -325,21 +290,81 @@ jobs:
       - name: Install .NET Tools
         run: |
           dotnet tool install -g Skyline.DataMiner.CICD.Tools.Packager
-          dotnet tool install -g Skyline.DataMiner.CICD.Tools.CatalogUpload
   
       - name: Create package name
         id: packageName
         run: |
-         tempName="${{ inputs.repository }}"
-         echo name=${tempName//[\"\/\\<>|:*?]/_} >> $GITHUB_OUTPUT
+          tempName="${{ inputs.repository }}"
+          echo name=${tempName//[\"\/\\<>|:*?]/_} >> $GITHUB_OUTPUT
         shell: bash
   
       - name: Create dmapp package
+        if: inputs.referenceType == 'tag'
         run: dataminer-package-create dmapp "${{ github.workspace }}" --type automation --version ${{ inputs.referenceName }} --output "${{ github.workspace }}" --name "${{ steps.packageName.outputs.name }}"
+  
+      - name: Create dmapp package
+        if: inputs.referenceType != 'tag'
+        run: dataminer-package-create dmapp "${{ github.workspace }}" --type automation --build-number ${{ inputs.runNumber }} --output "${{ github.workspace }}" --name "${{ steps.packageName.outputs.name }}"
+  
+      - uses: actions/upload-artifact@v4
+        with:
+          name: DataMiner Installation Package
+          path: "${{ github.workspace }}/${{ steps.packageName.outputs.name }}.dmapp"
+
+
+  artifact_creation_registration:
+    name: Artifact Registration and Upload
+    if: inputs.referenceType == 'tag'
+    runs-on: ubuntu-latest
+    needs: [validate_skyline_quality_gate,artifact_creation]
+    env:
+      result-artifact-id: none
+    outputs:
+      artifact-id: ${{ env.result-artifact-id }}
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Find branch
+        id: findBranch
+        run: |
+          #!/bin/bash
+          set -e  # Exit immediately if a command exits with a non-zero status.
+          
+          # Capture the branches containing the tag and process them
+          branches="$(git branch --contains tags/${{ inputs.referenceName }} -r | grep 'origin/' | grep -vE '.*/.*/' | sed 's#origin/##' | paste -sd ",")"
+          
+          # Append to GitHub Actions output
+          echo "branch=${branches}" >> $GITHUB_OUTPUT
+        shell: bash 
+
+      - name: Target Branch
+        id: showResult
+        run: echo "${{ steps.findBranch.outputs.branch }}"
+
+      - name: Retrieve Installation Package
+        id: retrieveInstallationPackage
+        uses: actions/download-artifact@v4
+        with:
+          name: DataMiner Installation Package
+          path: _DataMinerInstallationPackage
+          
+      - name: Find Installation package
+        id: findInstallationPackage        
+        run: |
+          IFS=$'\n'
+          echo dmappPackageName=$(find _DataMinerInstallationPackage -type f -name '*.dmapp') >> $GITHUB_OUTPUT
+          unset IFS
+        shell: bash  
+      - name: Install .NET Tools
+        run: |
+          dotnet tool install -g Skyline.DataMiner.CICD.Tools.CatalogUpload
   
       - name: Upload to Catalog
         id: uploadToCatalog
-        run: echo "id=$(dataminer-catalog-upload with-registration --path-to-artifact "${{ github.workspace }}/${{ steps.packageName.outputs.name }}.dmapp" --uri-sourcecode "${{ github.server_url }}/${{ github.repository }}" --artifact-version ${{ inputs.referenceName }} --branch "${{ steps.findBranch.outputs.branch }}" --dm-catalog-token ${{ secrets.api-key }})" >> $GITHUB_OUTPUT
+        run: echo "id=$(dataminer-catalog-upload with-registration --path-to-artifact "${{ steps.findInstallationPackage.outputs.dmappPackageName }}" --uri-sourcecode "${{ github.server_url }}/${{ github.repository }}" --artifact-version ${{ inputs.referenceName }} --branch "${{ steps.findBranch.outputs.branch }}" --dm-catalog-token ${{ secrets.api-key }})" >> $GITHUB_OUTPUT
  
       - name: (Release) Set artifact Id
         run: echo "result-artifact-id=${{ steps.uploadToCatalog.outputs.id }}" >> $GITHUB_ENV
