test parsing log

diff --git a/.github/workflows/DataMiner App Packages Master Workflow.yml b/.github/workflows/DataMiner App Packages Master Workflow.yml
--- a/.github/workflows/DataMiner App Packages Master Workflow.yml
+++ b/.github/workflows/DataMiner App Packages Master Workflow.yml
@@ -244,7 +244,6 @@ jobs:
         with:
           scanMetadataReportFile: .sonarqube/out/.sonar/report-task.txt
         continue-on-error: true
-        # Force to fail step after specific time.
         timeout-minutes: 5
         env:
           SONAR_TOKEN: ${{ secrets.sonarCloudToken }}
@@ -255,26 +254,20 @@ jobs:
           echo "Inspecting the outcome of the SonarCloud Quality Gate step..."
           echo "Outcome: ${{ steps.sonarcloud-quality-gate-check.outcome }}"
           
-          # Check if the previous step failed
-          if [ "${{ steps.sonarcloud-quality-gate-check.outcome }}" == "failure" ]; then
-            echo "The SonarCloud Quality Gate step failed. Checking the result..."
-            
-            # Debug the .result output
-            echo "Result Output: '${{ steps.sonarcloud-quality-gate-check.outputs.result }}'"
+          # Read the logs of the previous step from the default log file
+          echo "Capturing logs from the SonarCloud Quality Gate step..."
+          SONAR_LOG=$(cat $GITHUB_WORKSPACE/_temp/_runner_file_commands/continue-on-error.*.log || echo "Log file not found")
+          echo "SonarCloud Logs:"
+          echo "$SONAR_LOG"
       
-            # Check for 403 in the output
-            if [[ "${{ steps.sonarcloud-quality-gate-check.outputs.result }}" == *"403"* ]]; then
-              echo "SonarCloud Quality Gate failed with a 403 error."
-              echo "isSonarCloudValid=false" >> $GITHUB_OUTPUT
-            else
-              echo "SonarCloud Quality Gate failed, but no 403 error detected."
-              echo "isSonarCloudValid=true" >> $GITHUB_OUTPUT
-            fi
+          # Check if the logs contain the 403 error
+          if echo "$SONAR_LOG" | grep -q "The requested URL returned error: 403"; then
+            echo "403 error detected in the SonarCloud Quality Gate step."
+            echo "isSonarCloudValid=false" >> $GITHUB_OUTPUT
           else
-            echo "SonarCloud Quality Gate step succeeded."
+            echo "No 403 error detected in the SonarCloud Quality Gate step."
             echo "isSonarCloudValid=true" >> $GITHUB_OUTPUT
           fi
-        
       
       - name: Add Annotation for 403 Error
         if: ${{ steps.capture_sonarcloud_error.outputs.isSonarCloudValid == 'false' }}
