Validation for sonarCloudProjectName

diff --git a/.github/workflows/DataMiner App Packages Master Workflow.yml b/.github/workflows/DataMiner App Packages Master Workflow.yml
--- a/.github/workflows/DataMiner App Packages Master Workflow.yml
+++ b/.github/workflows/DataMiner App Packages Master Workflow.yml
@@ -53,6 +53,22 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Validate SonarCloud Project Name
+        id: validate-sonar-name
+        run: |
+          if [[ -z "${{ secrets.sonarCloudProjectName }}" ]]; then
+            echo "Error: sonarCloudProjectName is not set."
+            echo "Please create a SonarCloud project by visiting: https://sonarcloud.io/projects/create"
+            repo_url="https://github.com/${{ github.repository }}/settings/variables/actions"
+            echo "Then set a SONAR_NAME variable in your repository settings: $repo_url"
+            echo "Alternatively, if you do not wish to use the Skyline Quality Gate but intend to publish your results to the catalog, you may adjust/create your workflow to include a dotnet publish step as shown below:"
+            echo "    - name: Publish"
+            echo "      env:"
+            echo "        api-key: \${{ secrets.DATAMINER_KEY }}"
+            echo "      run: dotnet publish -p:Version=\"0.0.\${{ github.run_number }}\" -p:VersionComment=\"Iterative Development\" -p:CatalogPublishKeyName=\"api-key\""
+            exit 1
+          fi
+
       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
