test gh API

diff --git a/.github/workflows/Update Catalog Details.yml b/.github/workflows/Update Catalog Details.yml
--- a/.github/workflows/Update Catalog Details.yml
+++ b/.github/workflows/Update Catalog Details.yml
@@ -46,29 +46,29 @@ jobs:
             echo "ref type" ${{ inputs.referenceType }}
             echo "repository" ${{ inputs.repository }}
 
+        - name: Retrieve catalogIdentifier
+          id: get-catalog-variable
+          env:
+            GH_TOKEN: ${{ github.token }}
+          run: |
+            catalogIdentifier=$(gh api --method GET /repos/${{ github.repository }}/actions/variables/catalogIdentifier --jq '.value' || echo "")
+            if [ -z "$catalogIdentifier" ]; then
+              catalogIdentifier=$(powershell -Command "[guid]::NewGuid().ToString()")
+              echo "catalogIdentifier not found or empty. Generated new GUID: $catalogIdentifier"
+              gh api --method POST /repos/${{ github.repository }}/actions/variables \
+                -f name=catalogIdentifier -f value=$catalogIdentifier
+            fi
+            echo "::set-output name=catalogIdentifier::$catalogIdentifier"
+
         - name: Install .NET Tools
           run: |
             dotnet tool install -g Skyline.DataMiner.CICD.Tools.CatalogUpload
             dotnet tool install -g Skyline.DataMiner.CICD.Tools.GitHubToCatalogYaml --prerelease
-
-        - name: Set new value
-          env:
-            GH_TOKEN: ${{ github.token }}
-          run: |
-            gh api `
-              --method PATCH `
-              -H "Accept: application/vnd.github+json" `
-              -H "X-GitHub-Api-Version: 2022-11-28" `
-              /repos/ORG/REPO/actions/variables/MY_VAR `
-              -f name='MY_VAR' `
-              -f value="1.2.3"
-          shell: pwsh
           
-
         - name: Create or Extend Catalog.yml
           run: |
-            github-to-catalog-yaml --workspace "${{ github.workspace }}" --github-token ${{ secrets.GITHUB_TOKEN }} --github-repository "${{github.repository }}"
-          
+            github-to-catalog-yaml --workspace "${{ github.workspace }}" --github-token ${{ secrets.GITHUB_TOKEN }} --github-repository "${{ github.repository }}" --catalog-identifier ${{ steps.get-catalog-variable.outputs.catalogIdentifier }}"
+       
         - name: Check if catalog.yml or manifest.yml exists
           id: check_files
           run: |
